Frontend:
  impl: Simple_rw_processor
  clock_ratio: 1
  num_expected_insts: 150
  traces: 
    - example_inst.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: LPDDR6
    org:
      preset: LPDDR6_2Gb_x24
      channel: 1
      rank: 1
    timing:
      preset: LPDDR6_6400

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 1000000
    plugins:

  AddrMapper:
    impl: ChRaBaRoCo_LPDDR6
